<?php

use Illuminate\Database\Seeder;

class RecruitmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('recruitments')->truncate();

        $recruitments = [
            [
                "vacancy" => "Senior PHP Developer (English)",
                "quantity" => 6,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cSYIoux-wpKUFcrRWemEIghk4R8rK4JDtVizj2Qya2lSpDlT0k3FVK_07iwxSGrmE6FzADcV2ilsFnFjxcxYEYznBAZXUhh1NxA05ZALQPxtkfwC55vKnWxj4nO5yN3DGRrs7ndeJNVn4h0gnS4O3_=w630-h380-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 1,
                "city_id" => 1,
                "career_id" => 1,
                "salary_id" => 1,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Back-end Developer (.Net/Java/NodeJS)",
                "quantity" => 5,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dECdKVa9eOIydxjN1lMoZXPo954ONzVR6WiKuYGlQyrYedaDJiz6Hqwwxzxmf_fLgllupTK9W5cF67gXsZ-_sIJ7UGBA061F6cq8jEyV23m2JgKB0_q9lN6SKSAoA0dn3iGGqhTULNV6Y5DCMe1HiF=s225-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 2,
                "type_of_work_id" => 2,
                "city_id" => 2,
                "career_id" => 2,
                "salary_id" => 2,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Jr/Sr React Native/ReactJS (Up to $2500)",
                "quantity" => 3,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fxnJU50os1nCzo62PeyNkTw-w2E9mZETYyRV02xjFsvhCwEnrMU9Y6URDoBF7B9pFWexceHsIl0uUEAwZuvjd0qh_91dAC8r9fox7KjLrnnz3vueDC2QuCVfZrhMBjdX7OUHILAhVJ185MLLNrtgar=s400-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 3,
                "type_of_work_id" => 3,
                "city_id" => 3,
                "career_id" => 3,
                "salary_id" => 3,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Middle/Senior Android Dev (Java, Kotlin)",
                "quantity" => 4,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dvwIFTwUwFPo-584b4236nB8_o4JvRjCYG1AQo1Q6sAQAwYwDEllxtsvWxwAgEiPlMaXHgqIghChUCd-nfBTpu8qfrw_igVlzxm0kgpn-gYxlKiZeYzlS9xkhMI11Dus_i4e96MeLZeHPFz7bt_xEI=w500-h429-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 4,
                "type_of_work_id" => 4,
                "city_id" => 1,
                "career_id" => 4,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "iOS Developer (Swift, OOP, MVC)",
                "quantity" => 1,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f6OLBadR2jeqcvbv8ZEkrNptt2EuWY_532x2JynYCPffu8jlHtHbXPF4u_BzboqpiNe7a2T6iX1cGXEd6EumoHRs77GsoIH12S1zG950Kp023HXDU3QL8kopmUyPXB3wMO5eL_R3HfjnFSJeE9mzBG=s225-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 2,
                "city_id" => 3,
                "career_id" => 5,
                "salary_id" => 5,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "02 PHP Developers (MySQL,NoSQL)",
                "quantity" => 6,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dGqId1Rt39NxcJDcQ4E9KdKVHZEtuz52O-6JKRS7h43ylVgu5yrP6icKQopqNP662yhmw_hRV-Y3cLPGWfo2aoXlvodPiGEbjRDks19Q_FLnJfFLxqgcWPx88mt5cVnVK2TGnQDJxE_ZC3h3glxxBW=w230-h219-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 4,
                "type_of_work_id" => 2,
                "city_id" => 2,
                "career_id" => 6,
                "salary_id" => 1,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "05 C/C++ Developers",
                "quantity" => 2,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cgmJW4vQ61gR_O_uFTAgnjYgWUH9gr938K4yd5Z1wJIZFUaTt1tWNEvTf5ypvfWcRZeqLU21SF-YfDhIrAWUWdAYzjd6-QLp53P4v6GIBpy5htRoRIFCori1SRJ6Cl3gII8VGdAQK5O-F5y4RXzxob=s225-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 5,
                "type_of_work_id" => 2,
                "city_id" => 3,
                "career_id" => 7,
                "salary_id" => 2,
                "active" => 1,
                "order" => 1,
            ],
            [
                "vacancy" => "05 Java Developers (Spring, J2EE)",
                "quantity" => 12,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eoGoLWYChEtVghAper2hWEtyI4LPLSVe1FXSD_rXPzls1jjWFQbIINCEc4BOU0pUYKpX3kNteI154ikiUHhs8s-GQPvCbpFw71d-Z3mQAUK3Wry6wCPoGCZdC5ZdThWh_g4UjWNIy1yKFYy2Mj6qks=s200-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 5,
                "type_of_work_id" => 2,
                "city_id" => 2,
                "career_id" => 8,
                "salary_id" => 3,
                "active" => 1,
                "order" => 1,
            ],
            [
                "vacancy" => "Mobile Dev (Android/iOS/React Native)",
                "quantity" => 11,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cFUhOVReowQ-8Bs_pQJiqnAUT0m0bwSfzlb5fZITxH4zaz51ffdF4d2sQ0ZmWqdXuu5vhke-rqi71rjSqKvUqLYS-ojeHPLIGU9EifBt-noRv98k49nJXzLWA7tyP-HojvgF-oPtt_LA9uW9NDjNXq=s400-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 1,
                "city_id" => 1,
                "career_id" => 1,
                "salary_id" => 1,
                "active" => 1,
                "order" => 1,
            ],
            [
                "vacancy" => "Tester Manager (QA/ AC)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3djux71wFBwsyGO5YTO0zdQVgMIkZBYWn0BeFTHX0GQG7UMR4HnAo5pmSnjNvqh06hQA4I1CfO2xUZTnPIa4xvnPTvrM4IvZm5L7vWDHhQ0Mval1Y6FLd3wJuKqSYHPu4kD8BK7HJdETF0bMcn395ow=s225-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 2,
                "salary_id" => 4,
                "active" => 1,
                "order" => 1,
            ],
            [
                "vacancy" => "10 Mid-Senior-Tech Lead - PHP Developers",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cO0sjyGIk1rDzdhw9ux_1e-gE6wxLG3O_dix1RXe_It9E1LxtEehhAAzAAj-ciBxxK0Q7vRTVBJ7woJDHL1bvqer6t4hxwSaNK72qge-8cSR9KqVx7nJK-3lE2vNmt-8KhEutvV9oCgFSLOllYGBI3=s979-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 2,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 3,
                "salary_id" => 4,
                "active" => 1,
                "order" => 1,
            ],
            [
                "vacancy" => "Senior PHP Developer (PHP, MySQL)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3d6u7x_gmexXSvrI5EIzRlro6iJQJUFVh9_bllJ8DfQSNvH3IEwVlMv1P9s3q2S-UvVEJDnspTh6MgKOrlbeFIlw7PcTt6sN002SahGAt7R9ItwkS_PurLYXDXXYWSPzwKSn_J1rTGhBYlZpfgXR8ef=w271-h186-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 2,
                "city_id" => 2,
                "career_id" => 4,
                "salary_id" => 4,
                "active" => 1,
                "order" => 1,
            ],
            [
                "vacancy" => "3 PHP Dev (JavaScript, HTML5) Upto 1500$",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fQtuDHrpcqfvTlqu6SfeZoiTR2pwMieZD3VDZnwN_JRGkiopH7R-TqtafwCUULQy9kddsUYuGkF1xd0AE85nTEm5-cWK_V5JdDyNvxqecIsT291u9lp1qGZE26dgtm3HC0OI0NhymwrD-vqxgvqtY7=s225-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 3,
                "career_id" => 5,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "PHP Developer (Laravel, ReactJS)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dKH6hERP8VVvn6QSgbLhLqWlFRCTTYigudwOyxtiPxJ1HHTRqLuP0GC0UGzilTjCL7iEAgqMWez0v3xQe0Lp1yBbra6H0uNgID7KjS3cQd-rUCBmzPy12j82M7vn3VFWGr_3z9YenUcxohO7l2XJXS=w257-h196-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 6,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Dev Operations Application (C#, PHP)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f_bKb_0VVEgP5cQdia8ye_2IZh6tVP5FCmWmqCyK8edfQgKGRtYstXBPHP5n2y6ddijQuT0_4TulbxAmIyicESauvrqVjvycfGMB750RgH7bJ9QeL0Dv4-stm8GF3HTLhKbug9bwbma8znLcfF0kSP=w500-h389-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 2,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 7,
                "salary_id" => 2,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Web Engineer (Java, PHP, Japanese N2)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3c6b7D53oTVa38aN_YixYtTyp5RJdapJseItIaHhmklJL_kiRGl2FeyU5ZIiZud60jp8bXV_DWsNsr7t0gVtoUWOjAZDI4bIngVzELl3ZJW03-Zw8AsFtu3fgh3-HkcnFwK7zYje0Qu_C0ZcDQEiwzd=s300-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 3,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 8,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Web PHP Developer (Laravel, Wordpress)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3en-akyroGmf_of_C4W31PschqE1lnnYA4Ug8aYndpssfJMDpyVklLZ4MU1xH3cU8fBKIBL2pXwBYcamLTEFPXdKsnPuoGsMKW0po1zVv3mhCcT6zxdqWZJkDdWGqQNcx9dRtWZ44jZJ79Aj0cLg5eE=s225-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 3,
                "career_id" => 1,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "03 PHP Team Leaders",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fxnJU50os1nCzo62PeyNkTw-w2E9mZETYyRV02xjFsvhCwEnrMU9Y6URDoBF7B9pFWexceHsIl0uUEAwZuvjd0qh_91dAC8r9fox7KjLrnnz3vueDC2QuCVfZrhMBjdX7OUHILAhVJ185MLLNrtgar=s400-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 2,
                "salary_id" => 4,
                "active" => 0,
                "order" => 0,
            ],
            [
                "vacancy" => "02 PHP Developers (MySQL,NoSQL)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cGh2TvLWCdPEABlDhPgdlzdQj_Hxr3MBZ2JJMYAb_hKt5uivjZYIVbWpND1MLNFw36XRtpu5AETjkGDDBYwS7GglAtTRCxGuIpLw__ZDrwLdnLbgKNWMCwg2NOObEQWJccfVUpuislm4YeQU_YfH9l=w533-h400-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 3,
                "salary_id" => 3,
                "active" => 0,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Dev/Team Leader (PHP, JavaScipt)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cvZ01M65_rGczTFIfzoUcdoG9b1XFYSvu7TrF8TXWDhaGicCcvitZrYQb_G1YthVfONyf5s-k44rmfkOa8osua_zw5P_L078C4cNBWLkIoofW_X9BJDCBSvtAP4XooUgdP3ZYFiUqpUCU4tshdg_UD=s225-no",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 1,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 4,
                "salary_id" => 4,
                "active" => 0,
                "order" => 0,
            ],
            [
                "vacancy" => "Java Developer (.NET, PL/SQL)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cVDAWXkY_dhdW6tuPwV_KDUAlioZYzQUqeNZ4DXNF9C4fnLrBxC-_t_D7ppSqP0vSA6y9rV-6p4mN5HBSRB8u8aqeulhGBGEdPBs8MV_U7q7A-AGnt1PvzCQR_KqFLyqT-0qLjTRPFGsHMd4DEQ9qM=s320-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 2,
                "rank_id" => 4,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 5,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Frontend Developer (ReactJS, HTML, CSS)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dECdKVa9eOIydxjN1lMoZXPo954ONzVR6WiKuYGlQyrYedaDJiz6Hqwwxzxmf_fLgllupTK9W5cF67gXsZ-_sIJ7UGBA061F6cq8jEyV23m2JgKB0_q9lN6SKSAoA0dn3iGGqhTULNV6Y5DCMe1HiF=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 2,
                "rank_id" => 1,
                "type_of_work_id" => 4,
                "city_id" => 2,
                "career_id" => 6,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "WordPress Developer (PHP)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dvwIFTwUwFPo-584b4236nB8_o4JvRjCYG1AQo1Q6sAQAwYwDEllxtsvWxwAgEiPlMaXHgqIghChUCd-nfBTpu8qfrw_igVlzxm0kgpn-gYxlKiZeYzlS9xkhMI11Dus_i4e96MeLZeHPFz7bt_xEI=w500-h429-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 3,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 3,
                "career_id" => 7,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Java Developer (Spring, eclipse,web)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cYYl-2xTn42bd8kSdGNitMZvnXl_LL_JpMBbm1xVHayM-f7kj185A_Ws87tDc7kepM1Xmtxhfxlygx7u39Inp9QaHV8ONOPCysXZS2wMB2ybNs8yaFGalsL3JgmcbTrvlaIons6jpac1YXxidv_E0D=w500-h378-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 3,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 8,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Frontend Developer (ReactJS, JavaScript)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f6OLBadR2jeqcvbv8ZEkrNptt2EuWY_532x2JynYCPffu8jlHtHbXPF4u_BzboqpiNe7a2T6iX1cGXEd6EumoHRs77GsoIH12S1zG950Kp023HXDU3QL8kopmUyPXB3wMO5eL_R3HfjnFSJeE9mzBG=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 4,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 1,
                "career_id" => 1,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Mobile Developer (iOS/Android)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dGqId1Rt39NxcJDcQ4E9KdKVHZEtuz52O-6JKRS7h43ylVgu5yrP6icKQopqNP662yhmw_hRV-Y3cLPGWfo2aoXlvodPiGEbjRDks19Q_FLnJfFLxqgcWPx88mt5cVnVK2TGnQDJxE_ZC3h3glxxBW=w230-h219-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 4,
                "rank_id" => 5,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 2,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Ruby on Rails Developer",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cgmJW4vQ61gR_O_uFTAgnjYgWUH9gr938K4yd5Z1wJIZFUaTt1tWNEvTf5ypvfWcRZeqLU21SF-YfDhIrAWUWdAYzjd6-QLp53P4v6GIBpy5htRoRIFCori1SRJ6Cl3gII8VGdAQK5O-F5y4RXzxob=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 5,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 3,
                "salary_id" => 5,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "DevOps/System Admin Engineer",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eoGoLWYChEtVghAper2hWEtyI4LPLSVe1FXSD_rXPzls1jjWFQbIINCEc4BOU0pUYKpX3kNteI154ikiUHhs8s-GQPvCbpFw71d-Z3mQAUK3Wry6wCPoGCZdC5ZdThWh_g4UjWNIy1yKFYy2Mj6qks=s200-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 5,
                "rank_id" => 6,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 4,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "GAME Developer (Mobile Game - Cocos)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cFUhOVReowQ-8Bs_pQJiqnAUT0m0bwSfzlb5fZITxH4zaz51ffdF4d2sQ0ZmWqdXuu5vhke-rqi71rjSqKvUqLYS-ojeHPLIGU9EifBt-noRv98k49nJXzLWA7tyP-HojvgF-oPtt_LA9uW9NDjNXq=s400-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 6,
                "rank_id" => 1,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 5,
                "salary_id" => 5,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Delivery Manager - Up to 4000$",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3djux71wFBwsyGO5YTO0zdQVgMIkZBYWn0BeFTHX0GQG7UMR4HnAo5pmSnjNvqh06hQA4I1CfO2xUZTnPIa4xvnPTvrM4IvZm5L7vWDHhQ0Mval1Y6FLd3wJuKqSYHPu4kD8BK7HJdETF0bMcn395ow=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 6,
                "rank_id" => 6,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 6,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Sr Frontend Developers x5 (JavaScript)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cO0sjyGIk1rDzdhw9ux_1e-gE6wxLG3O_dix1RXe_It9E1LxtEehhAAzAAj-ciBxxK0Q7vRTVBJ7woJDHL1bvqer6t4hxwSaNK72qge-8cSR9KqVx7nJK-3lE2vNmt-8KhEutvV9oCgFSLOllYGBI3=s979-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 7,
                "rank_id" => 6,
                "type_of_work_id" => 6,
                "city_id" => 3,
                "career_id" => 7,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Java Backend Engineer (Spring, MySQL)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3d6u7x_gmexXSvrI5EIzRlro6iJQJUFVh9_bllJ8DfQSNvH3IEwVlMv1P9s3q2S-UvVEJDnspTh6MgKOrlbeFIlw7PcTt6sN002SahGAt7R9ItwkS_PurLYXDXXYWSPzwKSn_J1rTGhBYlZpfgXR8ef=w271-h186-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 7,
                "rank_id" => 6,
                "type_of_work_id" => 3,
                "city_id" => 1,
                "career_id" => 8,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "React Native Developer",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fQtuDHrpcqfvTlqu6SfeZoiTR2pwMieZD3VDZnwN_JRGkiopH7R-TqtafwCUULQy9kddsUYuGkF1xd0AE85nTEm5-cWK_V5JdDyNvxqecIsT291u9lp1qGZE26dgtm3HC0OI0NhymwrD-vqxgvqtY7=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 8,
                "rank_id" => 4,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 1,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Backend Developer (AI product)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dKH6hERP8VVvn6QSgbLhLqWlFRCTTYigudwOyxtiPxJ1HHTRqLuP0GC0UGzilTjCL7iEAgqMWez0v3xQe0Lp1yBbra6H0uNgID7KjS3cQd-rUCBmzPy12j82M7vn3VFWGr_3z9YenUcxohO7l2XJXS=w257-h196-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 8,
                "rank_id" => 6,
                "type_of_work_id" => 5,
                "city_id" => 3,
                "career_id" => 2,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Golang Developer",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f_bKb_0VVEgP5cQdia8ye_2IZh6tVP5FCmWmqCyK8edfQgKGRtYstXBPHP5n2y6ddijQuT0_4TulbxAmIyicESauvrqVjvycfGMB750RgH7bJ9QeL0Dv4-stm8GF3HTLhKbug9bwbma8znLcfF0kSP=w500-h389-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 9,
                "rank_id" => 5,
                "type_of_work_id" => 6,
                "city_id" => 2,
                "career_id" => 3,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Android devs (Java, Kotlin)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3c6b7D53oTVa38aN_YixYtTyp5RJdapJseItIaHhmklJL_kiRGl2FeyU5ZIiZud60jp8bXV_DWsNsr7t0gVtoUWOjAZDI4bIngVzELl3ZJW03-Zw8AsFtu3fgh3-HkcnFwK7zYje0Qu_C0ZcDQEiwzd=s300-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 9,
                "rank_id" => 1,
                "type_of_work_id" => 4,
                "city_id" => 1,
                "career_id" => 4,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "03 IT Support (Oracle, Database)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3en-akyroGmf_of_C4W31PschqE1lnnYA4Ug8aYndpssfJMDpyVklLZ4MU1xH3cU8fBKIBL2pXwBYcamLTEFPXdKsnPuoGsMKW0po1zVv3mhCcT6zxdqWZJkDdWGqQNcx9dRtWZ44jZJ79Aj0cLg5eE=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 10,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 1,
                "career_id" => 5,
                "salary_id" => 5,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Frontend Web Dev (JQuery, CSS, ReactJS)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fxnJU50os1nCzo62PeyNkTw-w2E9mZETYyRV02xjFsvhCwEnrMU9Y6URDoBF7B9pFWexceHsIl0uUEAwZuvjd0qh_91dAC8r9fox7KjLrnnz3vueDC2QuCVfZrhMBjdX7OUHILAhVJ185MLLNrtgar=s400-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 10,
                "rank_id" => 1,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 6,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Jun/Sen C++ Developer (700$ - 2000$)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cGh2TvLWCdPEABlDhPgdlzdQj_Hxr3MBZ2JJMYAb_hKt5uivjZYIVbWpND1MLNFw36XRtpu5AETjkGDDBYwS7GglAtTRCxGuIpLw__ZDrwLdnLbgKNWMCwg2NOObEQWJccfVUpuislm4YeQU_YfH9l=w533-h400-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 11,
                "rank_id" => 5,
                "type_of_work_id" => 5,
                "city_id" => 3,
                "career_id" => 7,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Product Owner",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cvZ01M65_rGczTFIfzoUcdoG9b1XFYSvu7TrF8TXWDhaGicCcvitZrYQb_G1YthVfONyf5s-k44rmfkOa8osua_zw5P_L078C4cNBWLkIoofW_X9BJDCBSvtAP4XooUgdP3ZYFiUqpUCU4tshdg_UD=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 11,
                "rank_id" => 6,
                "type_of_work_id" => 6,
                "city_id" => 3,
                "career_id" => 8,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Fullstack Java Developer (Java, ReactJS)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eVWCgyOaBgRHF08auO59_vmcprydejKU-5CrVwXK-Ow0IZ_NS56cXF5V-YOylhRsgatDPNA2AdUSYAJd76ULpaZRNVUS3PoZtX_xmfq4jybfNeC-YGtYGDbh3ylTf9eIJzMDkykvdI4byaOhO6vcyl=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 12,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 1,
                "career_id" => 1,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Software Engineer (Java, C++, Python)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eMizADAeYfANm2tPULTUcJq7Uj94rX0eYZU3OeisTJwP3ebRg1HGn0g0oSG46QITYmYN2T3RrskIE_avuLkjfkDUtSlk4uprvAJD2tls8AXqY4PhK2hx7lhdRY-gSDEkgdj6ITkjhV-p3pzU3TOQl0=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 12,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 2,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Jr/Sr .Net Developer(Xamarin,Mobile App)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eV1huNKUhMhltChWovZB2PBKRjc7H4XEm7W_rH-TmORR2Qz88kr2wwmBuXjPnFT9JKn7R6Tn3L9t72dCXrN7gB1s1goMOgPsWmyk0AE6nRchspKAM9CkoFmhFwIAAJsKp0clS_2o3cAhtLVpWuKIIh=w275-h183-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 13,
                "rank_id" => 1,
                "type_of_work_id" => 2,
                "city_id" => 3,
                "career_id" => 3,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "QA Lead, Core SDKs (QA QC, Tester)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dclsSsaSzCOtA2AnRdrdsv57fVK-JK-ybi3SVUndyXZANlIW5IVvxwwbD1Xp7eKT_GB4iwHL4A4wuC2kMgGFAX4lVuNfLojKeShYirycsR8u8VdcQQA1jjCtuJwalWpdOOhvYHwVj3i0asIX0cPbsF=s979-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 13,
                "rank_id" => 1,
                "type_of_work_id" => 4,
                "city_id" => 1,
                "career_id" => 4,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "10 Backend Dev (.Net / C# / ASP.NET)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fNSQg5piSPFV6k2C6Gqvg6XomqskyPWiW7lEn6_EZXmx-AxQTjlenwxihISBWDUB52F6bsfw8Mp2XZSpf3hUStQYqM3LcvJuN2OUZG6EG-rxjvdumF8zk0C6zRa70lLOwsNxKDjPya8cWe2aVtQAYa=s979-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 14,
                "rank_id" => 4,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 5,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "5 AI Engineers (C Language/C++/Python)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eC3uN7dCUHk3z_dfB6y0KPcDjKZQE0mEuNW_oyGGZJuQmySt2l3UNTo42OmswJADQf77z-z_Fas3Smd10Jo1UsBZEA9sej8CgX-Zgo9_4Lm7sOIB__mQWOSZjjeG-D_k56kMb9nAYHb1UC-P9btDfx=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 14,
                "rank_id" => 6,
                "type_of_work_id" => 6,
                "city_id" => 3,
                "career_id" => 6,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Web Dev (PHP/Angular/ReactJS)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dzQO8k9pWF_malh552ra8LcY2v68Ep8SFQYs_Iz_KOW46nOsMZItpcAcQ-bp5csxnxwwpubIJl-aCUogWFRrJls3Pt9siFHLFHHGQdCZduUnrkD7kgXgTaJukfTg0XZtPVF-DPYoNSyQn8Ktp0TTUq=s300-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 15,
                "rank_id" => 2,
                "type_of_work_id" => 3,
                "city_id" => 1,
                "career_id" => 7,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Backend Engineer (PHP, Laravel, OOP)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dXypBPWMfCS0NHgv8mNAS6ajDLJSwgsR5VIsMuSxg0T1amg94_v52TBvhjOSanK-ovpNW99tvj7pZ0eehc4UFsH1alPgLwWD_jCxSb59eQ1jCEf_BbPCT3jcZwg0k1esQAMHWuCwHyDiEF0vJr_uQt=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 15,
                "rank_id" => 1,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 8,
                "salary_id" => 5,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Software Deployment Engineer",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cnfMVqKleAudMWSXbedWp3zy6Tz3FrwIwTntHuuRTuyOO5cuHNfFdwjVFxz6DLD7M33Hd9cvyu2j6xlrnU3hdnWRWuw_tbcIZPkYyS659xfykF9G4PDLMeomyQW4ZMxVht86Dd_sWQoqkuWVb6fjhc=w216-h234-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 16,
                "rank_id" => 5,
                "type_of_work_id" => 5,
                "city_id" => 3,
                "career_id" => 1,
                "salary_id" => 1,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Mid/Sr. PHP Developer (Laravel, Symfony)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3d13jiVP_HnS73_j-BPps96t2BMJAVkoWHib8wxehKxGEqMtCi4XBoH-DjEstHbtLywS0fessEWHulmfFyqbxpRyxgQGtkgVcinn0K_ZggtBx_PauNYYG-9jWIQ4944mtGX_KumBsgr4iS9dr62BnHZ=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 16,
                "rank_id" => 1,
                "type_of_work_id" => 6,
                "city_id" => 2,
                "career_id" => 2,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Salesforce Dev (JavaScript/HTML5/CSS)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dXNevQ1qAZCVFPx9pKDW8hfNsJmU5vjFaT5ns_nnaMB1UECRUpfqnzBiH29pk5xbmZr8sqHnL7npUljmxkdhwNnMMU17wNp6O3UFXiydWCoeZqNwksw_EJVICbzVrcj-boZebyT7A5mjLe9qpdyisS=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 17,
                "rank_id" => 4,
                "type_of_work_id" => 5,
                "city_id" => 3,
                "career_id" => 3,
                "salary_id" => 5,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "PHP Middle Developer (My SQL, Laravel)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fI948UBu5GLy5hw7kodtF_RlW0XwZZve9GssOQki1tGeg23EQEbupg1A0aDEYGbx7wTVbuNBcakL8yV8o2b7a8Lp-IvijkINicExSkVTirdJgXGodb22Q1ecTb4BVM9_LuSaAM84c5zttQLIBT6xu3=s400-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 17,
                "rank_id" => 6,
                "type_of_work_id" => 5,
                "city_id" => 1,
                "career_id" => 4,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Java Developer (Spring, English)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3enpofUtnXfkxmNUhZPzzT1FI9xOOpDHFze87cbG0GUHB_UZD0C_trDvxcUCsHCMN3uGEKYC91rCu_GJLH_iSQnh6aDKi5Nvn6Ct9QsOdO5SOHjeriKdOfUQKvBFxEqeERBxxOWCHpaVYHset_o6UUK=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 18,
                "rank_id" => 1,
                "type_of_work_id" => 4,
                "city_id" => 2,
                "career_id" => 5,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "10 Tester ( QA/QC ) - Up to 1000$",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3d5BSIMarHpgQlNatEOzSaB6ml6jxcGfo3nVPEXtXsMKY11d2ZbalsprUToeRWX9hL4A7mO4zZh9eOjR8aDEAberz46KSig4qgL0HAjeB9OzLeubw6YEv39qv7Qyq0AJ-MDVSOLB6r_yltSYoL5Ruw0=w265-h190-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 18,
                "rank_id" => 2,
                "type_of_work_id" => 3,
                "city_id" => 3,
                "career_id" => 6,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Java Spring Developer - Up to $1500",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dDsBDo3u8lPAVvj4UVju92I9OJk513V8FNt-WrBnGVWxo1OCY1NPXDPZkMohvrSHvq7jGqdYnlf12Bt2hEFEJdmm3GykhprHdIJ5nBPRWzIAjSmsJYEpIDgyVgy2PEMzSQHdFnNfcMt3aaHVq0c0pk=s550-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 19,
                "rank_id" => 5,
                "type_of_work_id" => 3,
                "city_id" => 1,
                "career_id" => 7,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "[All levels] Java Developers -Up to $2k",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f_u-Wu5XD81yvAkrwSKi6b-xCv7DnnPgn6herVWzQkGDYyJd90kCxMsuRnISp28Zzeq6ay8mnPMppbk-qZHAGUeREk81H818O2nvy3dSw6VQ4bACQiy6l4e-dl5kJWtOXF0H3UcduqaLAwRRKcZ3NG=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 19,
                "rank_id" => 1,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 8,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "PHP Developer (React, English)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3d8Aw0yfU99q3gCvkw1a05HIS9EhFYRQqwRkCYaT_MWqeBdgbdzDOf8SJRkJ1be11JPuGWGy97VXBLVg_EcbR2LTQBrPBP6FW8enfrlST4Ac6SfEeQ5013JWkA_LOVXhvHXaJq6WLzEDMfWuSsqYQpK=s400-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 20,
                "rank_id" => 4,
                "type_of_work_id" => 1,
                "city_id" => 3,
                "career_id" => 1,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "ERP Project Manager",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3d_JFVqAIotGsSzcNV5T3kMYoKzdZNtrOE-mPny0JbQk96pyW8aS9VJ0lwo_jisnGtuuUl1FKQTh2IAEf7XFX8v80De0g9d-eeDq-WROZ83T2vf8ma2u2vQl2R0sZc9l3-Tan_y3xU5mhtEgSBlmbDk=w384-h266-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 20,
                "rank_id" => 5,
                "type_of_work_id" => 5,
                "city_id" => 1,
                "career_id" => 2,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Quality Assurance (Tester, QA QC)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fFaavEhl2pJhgDE06rR7pXGsRFQ5JjSIWQ-a_27nVrBVKy7Hs_KzOzA0cv4FnIeUxfATL-ESs-Un5zDZxCiSp0TLTRBNj9u8YRpZRC0xrfiCk43b_nflbqw2sMjF2XEloYq5lSSRKWYd9LO-L5P0Y_=w500-h309-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 21,
                "rank_id" => 5,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 3,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Lead DevOps (AWS, Python) 2200 - 3200$",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3e1EOYAl-e1ojkp0_ob4pnhI57HToVezGCXTVajikPo3KBGRQ3fLEMSLN2CWScDZ_I7aXtS0lZaipCAohyDQUhXhsai1Qp1iqsCQF_4ZiRufFUzDhht4aHyIZWYCwdq1nvNth1JOaKvokF9nTfx94i0=s300-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 21,
                "rank_id" => 1,
                "type_of_work_id" => 2,
                "city_id" => 3,
                "career_id" => 4,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Technical Architect",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f41ZY2SLn5z3dr2Ua3H2_0cSb8kUVOmOxbmpoQ4eWB9IkWCVK6BHkj702q9rFXk6am0MxkmJpoEWUwn9AVc9n9fybUYi19xZQKijDEhJmv4nejoAZAZEeb1kBDMmDom6mU74bxnXy_0Nq18Vdv92Hc=w242-h208-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 22,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 5,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Technical Lead (PHP + Infrastructure)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f7ehZtkApEwpmjJvFReikk9Fhvut_v-kTcQrpO4D6uQA1zggxum-XPyzttKbU8swobA7ANiTSpKr5Cz2DOpCqE9g6zFOTHqiflPVqJGPnAOfJWolC8c3vDUKQZ1JYFz7IOOvCyfLZNOjdVf2cDD5Ua=w300-h169-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 22,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 3,
                "career_id" => 6,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Web Developer (ReactJS) ~ 2300$",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3de1enybRqHM6aWokLMp7z26dvNed54lV30SjVSgBmQDr7Wj9nEaf4eVNsjHTdq02YeEwwaYG_D2TefP_A3CqbfJ53iAXYnW8EX6ceoKHLBI-NdnWiFWgPZaCjBGgtcGfndZ6Pr7dinE9BP25qxnZvN=w602-h302-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 23,
                "rank_id" => 5,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 7,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Sr BackEnd Dev (Java,Spring,Cloud)~2300$",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3d3s4pGlKSTc2yUW5S2SsfOLbZRVbNMLvomCyznz4F_KJcDDU-fOa2YRt-rzsboeQ3YYjH5SncN3fEBbTZcoftou2wncBABghhDNWCWoDQGk22eki8OTJLweuz7jFgdJzP3wfwsvcTwRRFTOZ6JEe8o=s600-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 23,
                "rank_id" => 6,
                "type_of_work_id" => 6,
                "city_id" => 3,
                "career_id" => 8,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Business Analyst (Database, English)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fAhni3EkBSkuagf7pihmmkZGY-z4QJbAuvE2DPvPLTz8ITPLGSx8V0nkDcdIEAV1pmVh3xvE03iOc1pJv6myOb9GEb00OQ1hKtSt3RSBxNJZVpnb2bj4IqAxZ1F9eI6bddfEaiTggR_KAkF8zTQjBs=s512-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 23,
                "rank_id" => 5,
                "type_of_work_id" => 5,
                "city_id" => 1,
                "career_id" => 1,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Big Data Engineer (Java/Python)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3em8wMxNKSaFBsde9I3BM4UejQS_2u272UyMiqv9-aqJwuMyMvJiCuu9bkEXl1szApUdepmtXjr5M9WusWjEY_FsQRVkGSuB8z5_AJH6Ng0q8dERnGAyQeOyxQWE7-1bfBIFWmLNPjxA-PFbR61mayg=s512-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 24,
                "rank_id" => 5,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 2,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior PHP Developer/ Technical Leader",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f78W6zx30JCtRKv7foSbK4_aS147SL06khAaLPAjJcltmWDRsaUZd01xMwNjNYRncKeOiLVX6tACXLn_vuej57J-_LRdES4WC5IlwDLi4uxvkaampTGDfW_hoFufChBUp7LBCd9isPz09gxLHjCu8q=s320-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 24,
                "rank_id" => 4,
                "type_of_work_id" => 4,
                "city_id" => 3,
                "career_id" => 3,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "5 Mobile Dev (Android/ iOS/React Native)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fCD1E6S-GY71jALO3MmkkBTnXX1wUFeoOip4q8h-5YvUdMVsBNRNWt6U9u_pYOqywPT-PaZg2ZmrDkTKIebF2JpmDpMSUQICzFc36eoUQ1RbBUIftTYhvNZ1EssUj3pACjIeYfaQxxYh9eAXN2OuA2=w268-h224-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 25,
                "rank_id" => 5,
                "type_of_work_id" => 3,
                "city_id" => 1,
                "career_id" => 4,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior NodeJS/AWS Developer (BONUS)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eUNZyQFcxcMFdMGrsaV7mF5suZahbvdBz3rjPeZ4X2rmGIuqzAy4h9VN8c2ZIHDHq72BMCYWEYyWhhSTcT8GtxIYAABfL294eVmT3dbKltexZEcm6jtWfob7up0h-LcIAxktsadWits_COTulEQ7i_=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 25,
                "rank_id" => 2,
                "type_of_work_id" => 2,
                "city_id" => 2,
                "career_id" => 5,
                "salary_id" => 5,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Business Analyst - Up to 1000$",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eTKZXZXooZ2rGSXoUKFpVfgT3uzI0jfVYpittNmIey5pUe85MsRKILvA0D0Z2wI8T3J_SYhDhh03R-WSJnMJ2FtW6fqTFuye_S_u5TL1baxHYWR1qXWwVtsfyc3tTWPelCRytw6Opw2hMZXM_Ng0ay=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 26,
                "rank_id" => 2,
                "type_of_work_id" => 2,
                "city_id" => 3,
                "career_id" => 6,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Java Backend (Python)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3f_bKb_0VVEgP5cQdia8ye_2IZh6tVP5FCmWmqCyK8edfQgKGRtYstXBPHP5n2y6ddijQuT0_4TulbxAmIyicESauvrqVjvycfGMB750RgH7bJ9QeL0Dv4-stm8GF3HTLhKbug9bwbma8znLcfF0kSP=w500-h389-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 26,
                "rank_id" => 6,
                "type_of_work_id" => 6,
                "city_id" => 1,
                "career_id" => 7,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "CLOUD ENGINEER (C++/Java/Python)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3eV1huNKUhMhltChWovZB2PBKRjc7H4XEm7W_rH-TmORR2Qz88kr2wwmBuXjPnFT9JKn7R6Tn3L9t72dCXrN7gB1s1goMOgPsWmyk0AE6nRchspKAM9CkoFmhFwIAAJsKp0clS_2o3cAhtLVpWuKIIh=w275-h183-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 27,
                "rank_id" => 1,
                "type_of_work_id" => 5,
                "city_id" => 2,
                "career_id" => 8,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Mobile Hybrid Dev (React Native, Ionic)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dclsSsaSzCOtA2AnRdrdsv57fVK-JK-ybi3SVUndyXZANlIW5IVvxwwbD1Xp7eKT_GB4iwHL4A4wuC2kMgGFAX4lVuNfLojKeShYirycsR8u8VdcQQA1jjCtuJwalWpdOOhvYHwVj3i0asIX0cPbsF=s979-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn.
                                          - Đào tạo vận hành sản phẩm dịch vụ, chuyển giao công nghệ.",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn.
                                          - Hỗ trợ 100% chi phí ăn trưa tại Công ty với những bữa cơm đủ dinh dưỡng, ngon lành, sạch sẽ, đảm bảo ATVSTP.",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.
                                          - Có kinh nghiệm về Log framework (Log back, log4j, …).
                                          - Có kiến thức tốt về Design Patterns (IOC, Singleton, Proxy, MVC, etc. …)",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 27,
                "rank_id" => 1,
                "type_of_work_id" => 4,
                "city_id" => 3,
                "career_id" => 1,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Senior Frontend ReactJS Dev (JavaScript)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dXNevQ1qAZCVFPx9pKDW8hfNsJmU5vjFaT5ns_nnaMB1UECRUpfqnzBiH29pk5xbmZr8sqHnL7npUljmxkdhwNnMMU17wNp6O3UFXiydWCoeZqNwksw_EJVICbzVrcj-boZebyT7A5mjLe9qpdyisS=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 28,
                "rank_id" => 1,
                "type_of_work_id" => 6,
                "city_id" => 1,
                "career_id" => 2,
                "salary_id" => 2,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Frontend Software Engineer - $3500 Bonus",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3enpofUtnXfkxmNUhZPzzT1FI9xOOpDHFze87cbG0GUHB_UZD0C_trDvxcUCsHCMN3uGEKYC91rCu_GJLH_iSQnh6aDKi5Nvn6Ct9QsOdO5SOHjeriKdOfUQKvBFxEqeERBxxOWCHpaVYHset_o6UUK=s225-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn.
                                          - Maintain hệ thống đang được vận hành (fix bug,…).
                                          - Đọc & tìm hiểu tài liệu về hệ thống đang vận hành.",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn.
                                          - Lương tháng 13.
                                          - Định kỳ review lương 6 tháng/1 lần.",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.
                                          - Có kinh nghiệm với Java ít nhất 1 năm.
                                          - Biết cơ bản về JavaScript, HTML, CSS.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 28,
                "rank_id" => 1,
                "type_of_work_id" => 3,
                "city_id" => 3,
                "career_id" => 3,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Bridge Engineer (BrSE, Japanese)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dDsBDo3u8lPAVvj4UVju92I9OJk513V8FNt-WrBnGVWxo1OCY1NPXDPZkMohvrSHvq7jGqdYnlf12Bt2hEFEJdmm3GykhprHdIJ5nBPRWzIAjSmsJYEpIDgyVgy2PEMzSQHdFnNfcMt3aaHVq0c0pk=s550-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn.
                                          - Xây dựng các tài liệu phân tích, hướng dẫn người dùng đối với các ứng dụng công nghệ thông tin trong công ty.
                                          - Hỗ trợ người dùng công nghệ thông tin để xử ý, hướng dẫn, các vấn đề phát sinh trong quá trình sử dụng.",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn.
                                          - Tham dự các hoạt động ngoại khóa của công ty.
                                          - Thưởng lễ, tết theo thâm niên làm việc của nhân viên.
                                          - Tham gia các khóa đào tạo chuyên môn & kỹ năng phát triển nghề nghiệp.",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.
                                          - Có kinh nghiệm làm việc với ngôn ngữ lập trình: .NET, Java, Web React, PL/SQL (có kinh nghiệm nhiều hơn 01 ngôn ngữ hoặc một framework phổ biến là lợi thế).
                                          - Có kinh nghiệm làm việc và thiết kế CSDL trên DB MS SQL …",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 29,
                "rank_id" => 1,
                "type_of_work_id" => 2,
                "city_id" => 2,
                "career_id" => 4,
                "salary_id" => 6,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "Angular Developer (JavaScript, ReactJS)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3fxnJU50os1nCzo62PeyNkTw-w2E9mZETYyRV02xjFsvhCwEnrMU9Y6URDoBF7B9pFWexceHsIl0uUEAwZuvjd0qh_91dAC8r9fox7KjLrnnz3vueDC2QuCVfZrhMBjdX7OUHILAhVJ185MLLNrtgar=s400-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn
                                          - Phân tích và đưa ra kết luận về tính khả thi và thời gian hoàn thành.
                                          - Tiếp nhận, làm rõ yêu cầu điều chỉnh/phát triển phần mềm từ trưởng nhóm/bộ phận kinh doanh.",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn.
                                          - Cơ hội đạt được mức thưởng tài chính cao với kết quả làm việc tốt.
                                          - Chế độ phúc lợi cạnh tranh.",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.
                                          - Có kỹ năng làm việc nhóm, có tinh thần trách nhiệm cao.
                                          - Có kinh nghiệm lập trình native (Android hoặc iOS) tối thiểu 1 năm.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 29,
                "rank_id" => 3,
                "type_of_work_id" => 4,
                "city_id" => 2,
                "career_id" => 5,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "[Urgent] 10 QA/Tester (Tiếng Nhật)",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3dTc_75ukpvo5y41G2ghZBlZDLKaggFq1JQymkxD6nrdzXXMjgLSj1XWyhzNPANTHZ7MoPvF5_vQFTRjAYOFiSBMoSjk-hCzMQxnN6JOKTnbLcVMokbffrAYr9U88v_7mDA09MbbUk84l11m6bQoaVp=s400-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn.
                                          - Đề xuất giải pháp phát triển, tối ưu hiệu năng cho sản phẩm, thực hiện nghiên cứu các kỹ thuật và công nghệ mới cho sản phẩm.",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn.
                                          - Gói chăm sóc sức khỏe cao cấp và các hoạt động tập thể được thiết kế để đảm bảo sức khỏe thể chất và tinh thần cho bạn.",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.
                                          - Có thể sử dụng thành thạo 1 số công cụ như SVN, Git, Mantis.
                                          - Hiểu biết về lập trình an toàn (security), lập trình tối ưu (high performance).",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 30,
                "rank_id" => 6,
                "type_of_work_id" => 3,
                "city_id" => 2,
                "career_id" => 6,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
            [
                "vacancy" => "React Native Developer ( iOS/ Android )",
                "quantity" => 10,
                "end_date" => "2021-09-16",
                "photo" => "https://lh3.googleusercontent.com/pw/ACtC-3cAoONIKqzci1sELKMDK0Zz-q8HaCtB6BSWBe5nNmPLukGDTF8I6nOzn_irSxyhAg4SrngGmm3Xg8Lwlo8wuPcgYEu06x8qTSaG6eO4-ZzhmWKRF7FoDCYH0mRTtIDsf6cxlDbY8PmVfxoTuhU1nEJN=s205-no?authuser=0",
                "description" => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn.
                                          - Phát triển các ứng dụng phục vụ hàng triệu người dùng lĩnh vực truyền hình/video.
                                          - Phối hợp với bộ phận phát triển sản phẩm thiết kế luồng nghiệp vụ người dùng.",
                "entitlements" => "- Lương thoả thuận khi phỏng vấn.
                                          - Môi trường thân thiện, cởi mở và năng động giúp bạn thể hiện bản thân và cống hiến cho xã hội.",
                "job_requirements" => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.
                                          - Khả năng làm việc độc lập hoặc làm việc theo nhóm.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id" => 30,
                "rank_id" => 1,
                "type_of_work_id" => 6,
                "city_id" => 1,
                "career_id" => 7,
                "salary_id" => 4,
                "active" => 1,
                "order" => 0,
            ],
        ];

        foreach ($recruitments as $item) {
            App\Models\Recruitment::create([
                    'vacancy' => $item['vacancy'],
                    'quantity' => $item['quantity'],
                    'end_date' => $item['end_date'],
                    'photo' => $item['photo'],
                    'description' => $item['description'],
                    'entitlements' => $item['entitlements'],
                    'job_requirements' => $item['job_requirements'],
                    'requested_documents' => $item['requested_documents'],
                    'employer_id' => $item['employer_id'],
                    'rank_id' => $item['rank_id'],
                    'type_of_work_id' => $item['type_of_work_id'],
                    'city_id' => $item['city_id'],
                    'career_id' => $item['career_id'],
                    'salary_id' => $item['salary_id'],
                    'active' => $item['active'],
                    'order' => $item['order'],
                ]
            );
        }
        Schema::enableForeignKeyConstraints();
    }
}
