<?php

use Illuminate\Database\Seeder;

class RecruitmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('recruitments')->truncate();

        $recruitments = [
            [
                "vacancy"             => "Senior PHP Developer (English)",
                "quantity"            => 6,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-2.xx.fbcdn.net/v/t1.0-9/118765145_327484611904298_2050335863272059679_n.jpg?_nc_cat=111&_nc_sid=e007fa&_nc_ohc=7F_NecIZH7oAX_QcDRx&_nc_ht=scontent-hkg4-2.xx&oh=8fbe800960042aaa83d0aa8a963db426&oe=5F7BEBD2",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 1,
                "city_id"             => 1,
                "career_id"           => 1,
                "salary_id"           => 1,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "Back-end Developer (.Net/Java/NodeJS)",
                "quantity"            => 5,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.0-9/118923821_328803551772404_6217995185107940714_n.jpg?_nc_cat=109&_nc_sid=e007fa&_nc_ohc=sqluCfVrMu4AX_cpHZq&_nc_ht=scontent-hkg4-1.xx&oh=80980aac995e2c15336c5c5ebdc17ed2&oe=5FA403A6",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 2,
                "type_of_work_id"     => 2,
                "city_id"             => 2,
                "career_id"           => 2,
                "salary_id"           => 2,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "Jr/Sr React Native/ReactJS (Up to $2500)",
                "quantity"            => 3,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkt1-2.xx.fbcdn.net/v/t1.0-9/118774367_328803538439072_6404621321095124424_n.jpg?_nc_cat=110&_nc_sid=e007fa&_nc_ohc=fVoBxKeYu3MAX-T2YrZ&_nc_ht=scontent-hkt1-2.xx&oh=384fbd3e623f847fe2bb4c4f809d1c25&oe=5FA0BA34",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 3,
                "type_of_work_id"     => 3,
                "city_id"             => 3,
                "career_id"           => 3,
                "salary_id"           => 3,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "Middle/Senior Android Dev (Java, Kotlin)",
                "quantity"            => 4,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.0-9/118985807_328803491772410_7647524855638065534_n.jpg?_nc_cat=101&_nc_sid=e007fa&_nc_ohc=5Z9duhJM_s0AX9vpN0i&_nc_ht=scontent-hkg4-1.xx&oh=296bc29604c4bdd9dab49746e44b496f&oe=5FA235D8",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 4,
                "type_of_work_id"     => 4,
                "city_id"             => 4,
                "career_id"           => 4,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "iOS Developer (Swift, OOP, MVC)",
                "quantity"            => 1,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.0-9/118886354_328803485105744_9205328706301873004_n.jpg?_nc_cat=104&_nc_sid=e007fa&_nc_ohc=2x3cXhPXvC0AX8fca5w&_nc_ht=scontent-hkg4-1.xx&oh=ad99840ad9a737e0553554275802991b&oe=5FA32767",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 2,
                "city_id"             => 3,
                "career_id"           => 4,
                "salary_id"           => 5,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "02 PHP Developers (MySQL,NoSQL)",
                "quantity"            => 6,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.0-9/118845847_327484671904292_8661862930424249413_n.jpg?_nc_cat=106&_nc_sid=e007fa&_nc_ohc=eS0gSoS4pjoAX-sL0_x&_nc_oc=AQnXy1I-O-6lWWD_iHC2n1DDZ4isAQdQEfMDWG_nz_9f-dVuziEpKKuCaomuBz389kjNxoL4ff4NXrKG3iCZ9Qbe&_nc_ht=scontent-hkg4-1.xx&oh=59d795bdaf249c1500d65c6a7462ccdd&oe=5F7A1345",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 4,
                "type_of_work_id"     => 2,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 1,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "05 C/C++ Developers",
                "quantity"            => 2,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118770885_327484701904289_6136731341415458532_n.jpg?_nc_cat=102&_nc_sid=e007fa&_nc_ohc=Ha2F_7FI2ZsAX8HWvrs&_nc_ht=scontent.fdad1-1.fna&oh=57519cccd163a703d634b92441af8749&oe=5F79B718",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 3,
                "type_of_work_id"     => 2,
                "city_id"             => 3,
                "career_id"           => 1,
                "salary_id"           => 2,
                "active"              => 1,
                "order"               => 1,
            ],
            [
                "vacancy"             => "05 Java Developers (Spring, J2EE)",
                "quantity"            => 12,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118765221_327484731904286_9170747675258842922_n.jpg?_nc_cat=103&_nc_sid=e007fa&_nc_ohc=Lnbk3lg3x6QAX_X7MW1&_nc_ht=scontent.fdad1-1.fna&oh=88f226a283c33280d012c5abd08d9db9&oe=5F799382",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 2,
                "city_id"             => 4,
                "career_id"           => 2,
                "salary_id"           => 3,
                "active"              => 1,
                "order"               => 1,
            ],
            [
                "vacancy"             => "Mobile Dev (Android/iOS/React Native)",
                "quantity"            => 11,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118773005_327484721904287_4656347840852042509_n.jpg?_nc_cat=100&_nc_sid=e007fa&_nc_ohc=v4v6cbrzOdIAX8O-0HY&_nc_ht=scontent.fdad1-1.fna&oh=4559e4eaf9d09c6d4318391cf3ec3c6e&oe=5F7A55AA",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 1,
                "city_id"             => 1,
                "career_id"           => 1,
                "salary_id"           => 1,
                "active"              => 1,
                "order"               => 1,
            ],
            [
                "vacancy"             => "Tester Manager (QA/ AC)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/118694107_327484775237615_1285612477250457215_n.jpg?_nc_cat=107&_nc_sid=e007fa&_nc_ohc=zVW-r_RfK_oAX-ZrCGr&_nc_ht=scontent.fdad2-1.fna&oh=e87e05aec0df970ba98a03391a76230d&oe=5F7C5DB4",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 1,
            ],
            [
                "vacancy"             => "10 Mid-Senior-Tech Lead - PHP Developers",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/p960x960/118790165_328803518439074_3229632315449862233_o.jpg?_nc_cat=108&_nc_sid=e007fa&_nc_ohc=BZS3gI3CdxsAX-ibIq4&_nc_ht=scontent.fdad2-1.fna&tp=6&oh=7b022df446a9e69e5cb65dcb5fbd1a92&oe=5F7E50E6",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 1,
            ],
            [
                "vacancy"             => "Senior PHP Developer (PHP, MySQL)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118886354_328803485105744_9205328706301873004_n.jpg?_nc_cat=104&_nc_sid=e007fa&_nc_ohc=RErTsuGOI6gAX_xD0SS&_nc_ht=scontent.fdad1-1.fna&oh=14b6eba1c404f6f24738185d8f30a473&oe=5F7B9A67",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 1,
            ],
            [
                "vacancy"             => "3 PHP Dev (JavaScript, HTML5) Upto 1500$",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/118985807_328803491772410_7647524855638065534_n.jpg?_nc_cat=101&_nc_sid=e007fa&_nc_ohc=Ehu0gi3yb0AAX-tjnJv&_nc_ht=scontent.fdad2-1.fna&oh=f7b13655c0601270af17d378ad3e4709&oe=5F7E9D58",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "PHP Developer (Laravel, ReactJS)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/118774367_328803538439072_6404621321095124424_n.jpg?_nc_cat=110&_nc_sid=e007fa&_nc_ohc=5FqUXiaor6oAX-BHrUi&_nc_ht=scontent.fdad2-1.fna&oh=7aa5f96d53c8d4da3886656f64f2cc0c&oe=5F7D21B4",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "Dev Operations Application (C#, PHP)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/118923821_328803551772404_6217995185107940714_n.jpg?_nc_cat=109&_nc_sid=e007fa&_nc_ohc=Kk1tNMQQFk8AX8S6MqQ&_nc_ht=scontent.fdad2-1.fna&oh=940a570e8bbf56e59e9a9858062099c5&oe=5F7C76A6",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "Web Engineer (Java, PHP, Japanese N2)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/118953462_328803575105735_8091656253710563762_n.jpg?_nc_cat=110&_nc_sid=e007fa&_nc_ohc=DC0AvOFWJzIAX_jr2Om&_nc_ht=scontent.fdad2-1.fna&oh=1453d00c437cc01bc0f23f48f84c27e1&oe=5F7C1869",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "Web PHP Developer (Laravel, Wordpress)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/118886546_328803588439067_6848063529537823197_n.jpg?_nc_cat=108&_nc_sid=e007fa&_nc_ohc=Vp9BXNq3Te8AX8WC9YZ&_nc_ht=scontent.fdad2-1.fna&oh=5b50d9250cda1a2c8928ca83dc7aab28&oe=5F7CF2B7",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 0,
            ],
            [
                "vacancy"             => "03 PHP Team Leaders",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/118812025_328803598439066_790218698730946046_n.jpg?_nc_cat=101&_nc_sid=e007fa&_nc_ohc=ff-_zKcvDuMAX-h1dM-&_nc_ht=scontent.fdad2-1.fna&oh=207edadad84f57dab8c04775304d51a9&oe=5F7BAF4B",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 0,
                "order"               => 0,
            ],
            [
                "vacancy"             => "02 PHP Developers (MySQL,NoSQL)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.0-9/p960x960/118790165_328803518439074_3229632315449862233_o.jpg?_nc_cat=108&_nc_sid=e007fa&_nc_ohc=isGp0aRK-Q8AX-pPVhx&_nc_ht=scontent-hkg4-1.xx&tp=6&oh=6d791b47100c238566c843415dcc302a&oe=5FA1E966",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 0,
                "order"               => 0,
            ],
            [
                "vacancy"             => "Senior Dev/Team Leader (PHP, JavaScipt)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118844309_328803645105728_5517288109059921635_n.jpg?_nc_cat=100&_nc_sid=e007fa&_nc_ohc=cnr17gLQfdUAX8aHZ_V&_nc_ht=scontent.fdad1-1.fna&oh=c1c0715a348b80c9d7dcf8d93170a38c&oe=5F7C8DA6",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 0,
                "order"               => 0,
            ],
        ];

        foreach ($recruitments as $item) {
            App\Models\Recruitment::create([
                    'vacancy'             => $item['vacancy'],
                    'quantity'            => $item['quantity'],
                    'end_date'            => $item['end_date'],
                    'photo'               => $item['photo'],
                    'description'         => $item['description'],
                    'entitlements'        => $item['entitlements'],
                    'job_requirements'    => $item['job_requirements'],
                    'requested_documents' => $item['requested_documents'],
                    'employer_id'         => $item['employer_id'],
                    'rank_id'             => $item['rank_id'],
                    'type_of_work_id'     => $item['type_of_work_id'],
                    'city_id'             => $item['city_id'],
                    'career_id'           => $item['career_id'],
                    'salary_id'           => $item['salary_id'],
                    'active'              => $item['active'],
                    'order'               => $item['order'],
                ]
            );
        }
        Schema::enableForeignKeyConstraints();
    }
}
