<?php

use Illuminate\Database\Seeder;

class RecruitmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('recruitments')->truncate();

        $recruitments = [
            [
                "vacancy"             => "Senior PHP Developer (English)",
                "quantity"            => 6,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-2.xx.fbcdn.net/v/t1.0-9/118765145_327484611904298_2050335863272059679_n.jpg?_nc_cat=111&_nc_sid=e007fa&_nc_ohc=7F_NecIZH7oAX_QcDRx&_nc_ht=scontent-hkg4-2.xx&oh=8fbe800960042aaa83d0aa8a963db426&oe=5F7BEBD2",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 1,
                "city_id"             => 1,
                "career_id"           => 1,
                "salary_id"           => 1,
                "active"              => 1,
                "order"               => null,
            ],
            [
                "vacancy"             => "Back-end Developer (.Net/Java/NodeJS)",
                "quantity"            => 5,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118766458_327484608570965_6625297814813295197_n.jpg?_nc_cat=103&_nc_sid=e007fa&_nc_ohc=bR5bPPTN5jsAX879Gel&_nc_ht=scontent.fdad1-1.fna&oh=e31bb3bfe7a5e2d8a6433429fdaabb46&oe=5F7BE086",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 2,
                "type_of_work_id"     => 2,
                "city_id"             => 2,
                "career_id"           => 2,
                "salary_id"           => 2,
                "active"              => 1,
                "order"               => null,
            ],
            [
                "vacancy"             => "Jr/Sr React Native/ReactJS (Up to $2500)",
                "quantity"            => 3,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118736289_327484588570967_8183731743854301038_n.jpg?_nc_cat=103&_nc_sid=e007fa&_nc_ohc=oyDAb-Bu4_gAX8awG5d&_nc_ht=scontent.fdad1-1.fna&oh=e9869aa9568120b1afb0329e0dbd5d03&oe=5F7BAA35",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 3,
                "type_of_work_id"     => 3,
                "city_id"             => 3,
                "career_id"           => 3,
                "salary_id"           => 3,
                "active"              => 1,
                "order"               => null,
            ],
            [
                "vacancy"             => "Middle/Senior Android Dev (Java, Kotlin)",
                "quantity"            => 4,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118791713_327484651904294_6572265095667909527_n.jpg?_nc_cat=103&_nc_sid=e007fa&_nc_ohc=8uiVvNXlHZEAX9SSXbm&_nc_ht=scontent.fdad1-1.fna&oh=224d0c33992a14537069c67b87279794&oe=5F795400",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 4,
                "type_of_work_id"     => 4,
                "city_id"             => 4,
                "career_id"           => 4,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => null,
            ],
            [
                "vacancy"             => "iOS Developer (Swift, OOP, MVC)",
                "quantity"            => 1,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.0-9/118701959_327484668570959_2214400998092180398_n.jpg?_nc_cat=106&_nc_sid=e007fa&_nc_ohc=ZDjJLHVIT8IAX8f9sgg&_nc_ht=scontent-hkg4-1.xx&oh=8791c222b02558edc43b7930c7af25e5&oe=5F7BC2A6",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 2,
                "city_id"             => 3,
                "career_id"           => 4,
                "salary_id"           => 5,
                "active"              => 1,
                "order"               => null,
            ],
            [
                "vacancy"             => "02 PHP Developers (MySQL,NoSQL)",
                "quantity"            => 6,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.0-9/118845847_327484671904292_8661862930424249413_n.jpg?_nc_cat=106&_nc_sid=e007fa&_nc_ohc=eS0gSoS4pjoAX-sL0_x&_nc_oc=AQnXy1I-O-6lWWD_iHC2n1DDZ4isAQdQEfMDWG_nz_9f-dVuziEpKKuCaomuBz389kjNxoL4ff4NXrKG3iCZ9Qbe&_nc_ht=scontent-hkg4-1.xx&oh=59d795bdaf249c1500d65c6a7462ccdd&oe=5F7A1345",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 4,
                "type_of_work_id"     => 2,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 1,
                "active"              => 1,
                "order"               => null,
            ],
            [
                "vacancy"             => "05 C/C++ Developers",
                "quantity"            => 2,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118770885_327484701904289_6136731341415458532_n.jpg?_nc_cat=102&_nc_sid=e007fa&_nc_ohc=Ha2F_7FI2ZsAX8HWvrs&_nc_ht=scontent.fdad1-1.fna&oh=57519cccd163a703d634b92441af8749&oe=5F79B718",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 3,
                "type_of_work_id"     => 2,
                "city_id"             => 3,
                "career_id"           => 1,
                "salary_id"           => 2,
                "active"              => 1,
                "order"               => 1,
            ],
            [
                "vacancy"             => "05 Java Developers (Spring, J2EE)",
                "quantity"            => 12,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118765221_327484731904286_9170747675258842922_n.jpg?_nc_cat=103&_nc_sid=e007fa&_nc_ohc=Lnbk3lg3x6QAX_X7MW1&_nc_ht=scontent.fdad1-1.fna&oh=88f226a283c33280d012c5abd08d9db9&oe=5F799382",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 2,
                "city_id"             => 4,
                "career_id"           => 2,
                "salary_id"           => 3,
                "active"              => 1,
                "order"               => 2,
            ],
            [
                "vacancy"             => "Mobile Dev (Android/iOS/React Native)",
                "quantity"            => 11,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/118773005_327484721904287_4656347840852042509_n.jpg?_nc_cat=100&_nc_sid=e007fa&_nc_ohc=v4v6cbrzOdIAX8O-0HY&_nc_ht=scontent.fdad1-1.fna&oh=4559e4eaf9d09c6d4318391cf3ec3c6e&oe=5F7A55AA",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 1,
                "city_id"             => 1,
                "career_id"           => 1,
                "salary_id"           => 1,
                "active"              => 1,
                "order"               => 3,
            ],
            [
                "vacancy"             => "Tester Manager (QA/ AC)",
                "quantity"            => 10,
                "end_date"            => "2020-08-11",
                "photo"               => "https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/118694107_327484775237615_1285612477250457215_n.jpg?_nc_cat=107&_nc_sid=e007fa&_nc_ohc=zVW-r_RfK_oAX-ZrCGr&_nc_ht=scontent.fdad2-1.fna&oh=e87e05aec0df970ba98a03391a76230d&oe=5F7C5DB4",
                "description"         => "- Thực hiện các dự án công nghệ của công ty, theo từng giai đoạn",
                "entitlements"        => "- Lương thoả thuận khi phỏng vấn",
                "job_requirements"    => "- Tốt nghiệp Cao đẳng / Đại học hoặc tương đương về chuyên ngành CNTT phần cứng, mạng, hoặc các bằng cấp liên quan.",
                "requested_documents" => "- Đơn xin việc hoặc CV xin viêc",
                "employer_id"         => 1,
                "rank_id"             => 1,
                "type_of_work_id"     => 3,
                "city_id"             => 2,
                "career_id"           => 1,
                "salary_id"           => 4,
                "active"              => 1,
                "order"               => 4,
            ],
        ];

        foreach ($recruitments as $item) {
            App\Models\Recruitment::create([
                    'vacancy'             => $item['vacancy'],
                    'quantity'            => $item['quantity'],
                    'end_date'            => $item['end_date'],
                    'photo'               => $item['photo'],
                    'description'         => $item['description'],
                    'entitlements'        => $item['entitlements'],
                    'job_requirements'    => $item['job_requirements'],
                    'requested_documents' => $item['requested_documents'],
                    'employer_id'         => $item['employer_id'],
                    'rank_id'             => $item['rank_id'],
                    'type_of_work_id'     => $item['type_of_work_id'],
                    'city_id'             => $item['city_id'],
                    'career_id'           => $item['career_id'],
                    'salary_id'           => $item['salary_id'],
                    'active'              => $item['active'],
                    'order'               => $item['order'],
                ]
            );
        }
        Schema::enableForeignKeyConstraints();
    }
}
